-- ============================================================
-- dispatch_task
-- Dataset: burnsignal_scoring
-- Written by: coordination_agent (§3.6) and dispatch_service (§3.7).
-- Central operational record: one row per farmer per pipeline run
-- that requires outreach. This is the delivery-mechanism contract
-- (architecture.md §10) — a second BRICS implementation swaps
-- only the consumer of this table, not its schema.
-- ============================================================

CREATE TABLE IF NOT EXISTS `${GCP_PROJECT_ID}.burnsignal_scoring.dispatch_task`
(
  -- UUID generated by coordination_agent
  task_id          STRING    NOT NULL,

  -- Source plot
  plot_id          STRING    NOT NULL,

  -- Parent cluster
  cluster_id       STRING    NOT NULL,

  -- ── Routing (§3.6) ─────────────────────────────────────────
  -- 'kvk_worker'             → routed to extension worker (normal path)
  -- 'district_officer_queue' → no worker mapped; officer must resolve
  assignment_type  STRING    NOT NULL,

  -- NULL when assignment_type = 'district_officer_queue'
  worker_id        STRING,

  -- ── Equipment (§3.6) ────────────────────────────────────────
  -- NULL when no slot available within EQUIPMENT_MAX_DISTANCE_KM.
  -- Architecture Principle 4: task is NOT dispatched to farmer
  -- while equipment_ref IS NULL (status = 'escalation_required').
  equipment_ref    STRING,

  -- ── Script (§3.7) ───────────────────────────────────────────
  -- GCS path: gs://{GCS_AUDIO_BUCKET}/{task_id}.mp3
  -- NULL until dispatch_service generates the audio.
  script_ref       STRING,

  -- Full generated script text (in-lined for dashboard display).
  -- NULL until dispatch_service runs.
  script_text      STRING,

  -- TTS language code used: 'hi-IN' | 'pa-IN'
  tts_language     STRING,

  -- ── Status lifecycle ────────────────────────────────────────
  -- 'pending_script'      → coordination_agent created task; script not yet generated
  -- 'ready_for_delivery'  → script generated; ready for worker call-list
  -- 'escalation_required' → equipment_ref IS NULL or no worker mapping
  -- 'delivered'           → worker confirmed delivery (dashboard action)
  status           STRING    NOT NULL DEFAULT 'pending_script',

  -- ── Timestamps ──────────────────────────────────────────────
  created_at       TIMESTAMP NOT NULL,
  script_ready_at  TIMESTAMP,
  delivered_at     TIMESTAMP,

  -- Pipeline lineage
  pipeline_run_id  STRING,

  -- District code
  district_code    STRING    NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY status, worker_id, district_code
OPTIONS (
  description = 'Central dispatch task table. One row per farmer per pipeline run requiring outreach. '
                'Written by coordination_agent (routing + equipment) and dispatch_service (script). '
                'Status lifecycle: pending_script → ready_for_delivery → delivered '
                '(or → escalation_required if no equipment slot or no worker). '
                'This is the stable delivery-mechanism contract (architecture.md §10): '
                'a second BRICS-nation delivery system (SMS gateway, call centre, worker app) '
                'consumes this table unchanged. '
                'PII note: farmer contact is resolved from plot_registry at delivery time by '
                'the coordination_agent; this table itself stores only plot_id + worker_id '
                'to minimise PII surface (architecture.md §9.4). '
                'Partitioned by created_at; clustered by status and worker_id.'
);
