-- ============================================================
-- hotspot_clusters
-- Dataset: burnsignal_scoring
-- Written by: clustering_agent (§3.5)
-- One row per detected geographic/temporal cluster.
-- This is the A2A interoperability contract (architecture.md §10).
-- ============================================================

CREATE TABLE IF NOT EXISTS `${GCP_PROJECT_ID}.burnsignal_scoring.hotspot_clusters`
(
  -- UUID generated by clustering_agent at cluster creation time
  cluster_id         STRING    NOT NULL,

  -- Geographic centroid of all member plots (WGS-84)
  centroid           GEOGRAPHY,

  -- Mean burn_likelihood_score across member plots
  mean_score         FLOAT64   NOT NULL,

  -- Earliest scoring_window_end among member plots.
  -- Defines the cluster's actionable deadline.
  effective_deadline TIMESTAMP NOT NULL,

  -- Total number of member plots in this cluster
  plot_count         INT64     NOT NULL DEFAULT 0,

  -- DBSCAN run parameters captured for reproducibility
  cluster_eps_meters INT64,
  cluster_min_samples INT64,

  -- District / block metadata (denormalized for dashboard queries)
  district_code      STRING    NOT NULL,
  block_code         STRING,

  -- Pipeline lineage
  pipeline_run_id    STRING,
  clustered_at       TIMESTAMP NOT NULL
)
PARTITION BY DATE(effective_deadline)
CLUSTER BY district_code, mean_score
OPTIONS (
  description = 'Hotspot clusters produced by the DBSCAN clustering agent. '
                'Each row represents a geographic/temporal group of high-risk plots. '
                'effective_deadline = earliest scoring_window_end among member plots. '
                'This table is the stable A2A interoperability contract: '
                'a second BRICS-nation deployment consumes this schema unchanged '
                'with its own coordination_agent implementation (architecture.md §10). '
                'Partitioned by deadline date; clustered by district and score.'
);
